project/main/urls.py
from django.urls import path, include
from .views import *

app_name = "main"
urlpatterns = [
    path('', showindex, name="index"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('users/',include('users.urls')),
    path('<str:post_id>/create_comment/', create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment/<str:comment_id>', edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment/<str:comment_id>', update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment/<str:comment_id>', delete_comment, name="delete_comment"),
    path('create_guestbook/', create_guestbook, name="create_guestbook"),
    path('delete_comment/<int:id>', delete_guestbook, name="delete_guestbook"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', views.showintroduction, name="introduction"),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', mypage, name="mypage"),
    path('<int:id>/follow', follow, name="follow")
]

project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    followings=models.ManyToManyField("self", related_name="followers", symmetrical=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

project/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Post, Guestbook, Comment
from django.contrib.auth.models import User
# Create your views here.
def mypage(request, id):
    user=get_object_or_404(User, pk=id)
    comments=Comment.objects.filter(writer=user)
    context={
        'user': user,
        'comments': comments,
        'followings': user.profile.followings.all(),
        'followers': user.profile.followers.all(),
        'guestbooks': Guestbook.objects.all(),
    }
    return render(request, 'users/mypage.html', context)
    
def follow(request, id):
    user=request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

project/users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}
{% block content %}

<div class="container">
    <div class="new">
        <h2><a href="{%url 'main:new'%}">글 쓰기</a></h2>
    </div>
    <h1>{{user.username}}</h1>
    {% if request.user != user %}
        {% if request.user.profile in user.profile.followers.all %}
        <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
        {% else %}
        <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}
    <div>
    {% if posts %}

    {% for comment in comments %}
        <a href="{% url 'main:detail' comment.post.id %}">{{comment.content}}</a><hr>
    {% endfor %}
    
    {% else %}
        <div class="nonmessage">
            <h4>포스팅한 게시물이 없습니다!</h4>
        </div>
    </div>
    {% endif %}

    <div class="container">
        <h3>팔로워{{user.profile.followers.count}}명</h3>
        {% for follower in user.profile.follwers.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
        {% endfor %}
        <h3>팔로잉{{user.profile.followings.count}}명</h3>
        {% for following in user.profile.follwings.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{following.user.username}}</a>
        {% endfor %}
    </div>
</div>

{% endblock %}