project/main/urls.py
from django.urls import path, include
from .views import *

app_name = "main"
urlpatterns = [
    path('', showindex, name="index"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('users/',include('users.urls')),
    path('<str:post_id>/create_comment/', create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment/<str:comment_id>', edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment/<str:comment_id>', update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment/<str:comment_id>', delete_comment, name="delete_comment"),
    path('create_guestbook/', create_guestbook, name="create_guestbook"),
    path('delete_comment/<int:id>', delete_guestbook, name="delete_guestbook"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', views.showintroduction, name="introduction"),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/templates/shared/_header.html
{% load i18n %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Yusung's sns</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'introduction' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Album Review</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://www.facebook.com/profile.php?id=100003656653600">Facebook</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Instagram
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="https://www.instagram.com/ustar1210/">일상</a></li>
              <li><a class="dropdown-item" href="https://www.instagram.com/usfork/">앨범 리뷰</a></li>    
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            {% if user.is_authenticated %}
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'account_email' %}">Change e-mail</a></li>    
              </a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <a class="dropdown-item" href="#">            
                    <form method="post" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                    {% endif %}
                    <button type="submit">{% trans 'Sign Out' %}</button>
                    </form>
                </a>
            </li>
            </ul>
            {% else %}            
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'account_login' %}">log in</a></li>
                <li><a class="dropdown-item" href="{% url 'account_signup' %}">sign in</a></li>    
                </a></li>
            </ul>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>


{% endblock %}