project/main/urls.py
from django.urls import path, include
from .views import *

app_name = "main"
urlpatterns = [
    path('', showindex, name="index"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('users/',include('users.urls')),
    path('<str:post_id>/create_comment/', create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment/<str:comment_id>', edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment/<str:comment_id>', update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment/<str:comment_id>', delete_comment, name="delete_comment"),
    path('create_guestbook/', create_guestbook, name="create_guestbook"),
    path('delete_comment/<int:id>', delete_guestbook, name="delete_guestbook"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', views.showintroduction, name="introduction"),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', mypage, name="mypage"),
    path('<int:id>/follow', follow, name="follow")
]

project/project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SNS 메인페이지</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_base.css' %}">
    
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    {% block style&js %}
    {% endblock %}
</head>
<body>
    {% include 'shared/_header.html' %}

    <content>
        <div class="content">
        {% block content %}
        {% endblock %}
        </div>
        <div class="guestbook">
            <h2>Guest Book</h2>
            <div class="guestbooks">
                <hr>
                {% for g in guestbooks %}
                <div class="g">
                    <h5>{{g.body}}</h5>
                    <p><a href="{% url 'users:mypage' g.writer.id %}">작성자 : {{ g.writer }}</a></p>
                    <p>{{g.pub_date}}</p>
                    {% if user.username == g.writer.username %}
                    <a href="{% url 'main:delete_guestbook' g.id %}">삭제하기</a>
                    {% endif %}
                </div>
                <hr>
                {% endfor %}
            </div>    
            {% if user.is_authenticated %}
            <div class="new">
                <h5>방명록 작성하기</h5>
                <section>
                    <form action="{%url 'main:create_guestbook'%}" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <textarea type="text" name="body" id="" cols="30" rows="3"></textarea>
                        <button type="submit">완료</button>
                    </form>
                </section>
            </div>
            {% else %}
            <div class="nonmessage">
                <h5>로그인을 먼저 해주세요.</h5>
            </div>
            {% endif %}
        </div>
    </content>
    {% include 'shared/_footer.html' %}
</body>
</html>