project/main/urls.py
from django.urls import path, include
from .views import *

app_name = "main"
urlpatterns = [
    path('', showindex, name="index"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('users/',include('users.urls')),
    path('<str:post_id>/create_comment/', create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment/<str:comment_id>', edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment/<str:comment_id>', update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment/<str:comment_id>', delete_comment, name="delete_comment"),
    path('create_guestbook/', create_guestbook, name="create_guestbook"),
    path('delete_comment/<int:id>', delete_guestbook, name="delete_guestbook"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', views.showintroduction, name="introduction"),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', mypage, name="mypage"),
    path('<int:id>/follow', follow, name="follow")
]

project/main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set', through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name='dislikes_user_set', through='Dislike')
    def __str__(self):
        return self.title
    
    @property
    def summary(self):
        return self.body[:20]
    @property
    def like_count(self):
        return self.like_user_set.count()
    @property
    def dislike_count(self):
        return self.dislike_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.content

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'post'))

class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'post'))

class Guestbook(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    def __str__(self):
        return self.title

project/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Like, Dislike, Guestbook
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json


def showindex(request):
    posts = Post.objects.all()
    return render(request, 'main/index.html',{
        'posts':posts,
        'guestbooks': Guestbook.objects.all()

        })
 
def showintroduction(request):
    guestbooks = Guestbook.objects.all()
    return render(request, 'main/introduction.html', {
        'guestbooks': guestbooks,
    })

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    guestbooks = Guestbook.objects.all()
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html', {
        'post':post, 
        'comments':all_comments, 
        'guestbooks': guestbooks,
        })

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail', new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post' : edit_post})

def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST['title']
    update_post.writer =  request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.image = request.FILES.get('image')
    update_post.save()
    return redirect('main:detail', update_post.id)

def delete(request , id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect('main:index')

def create_comment(request, post_id):
    new_comment = Comment()
    new_comment.writer = request.user
    new_comment.content = request.POST['content']
    new_comment.post = get_object_or_404(Post, pk=post_id)
    new_comment.save()
    return redirect('main:detail', post_id)

def edit_comment(request, post_id, comment_id):
    target_post = Post.objects.get(id = post_id)
    edit_comment = Comment.objects.get(id = comment_id)
    return render(request, 'main/edit_comment.html', {'post':target_post, 'comment' : edit_comment})

def update_comment(request, post_id, comment_id):
    target_post = Post.objects.get(id = post_id)
    update_comment = Comment.objects.get(id=comment_id)
    update_comment.content = request.POST['content']
    update_comment.writer =  request.user
    update_comment.save()
    return redirect('main:detail', target_post.id)
  
def delete_comment(request , post_id, comment_id):
    target_post = Post.objects.get(id = post_id)
    delete_comment = Comment.objects.get(id = comment_id)
    delete_comment.delete()
    return redirect('main:detail', target_post.id)

@require_POST
@login_required
def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    post_like, post_like_created = Like.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    context = {
        "like_count" : post.like_count,
        "result" : result
    }
    return HttpResponse(json.dumps(context), content_type = "application/json")

@require_POST
@login_required
def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"
    context = {
        "dislike_count" : post.dislike_count,
        "result" : result
    }
    return HttpResponse(json.dumps(context), content_type = "application/json")



def create_guestbook(request):
    guestbook = Guestbook()
    guestbook.writer = request.user
    guestbook.pub_date = timezone.now()
    guestbook.body = request.POST['body']
    guestbook.save()
    return redirect('main:index')

def delete_guestbook(request , id):
    delete_guestbook = Guestbook.objects.get(id = id)
    delete_guestbook.delete()
    return redirect('main:index')

project/main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}
<section>
        <div class="post">
            <h1>{{post.title}}</h1>
            <h5>{{ post.pub_date }}</h5>
            <br>
            {% if post.image %}
                <div class="picBox pd100">
                    <div class="pic" >
                        <p><img src="{{ post.image.url }}" alt="사진"></p>
                    </div>
                </div>
                <br>
            {% endif %}
            <p>{{post.body}}</p>
            <br>
            <span href="#" class="like" name ="{{post.id}}" value="Like">
                {% if user in post.like_user_set.all %}
                <span class="alt-service-icon">
                    <i class="fas fa-heart fa-2x" id ="like-icon" style="color:red;"></i>
                </span>
                {% else %}
                <span class="alt-service-icon">
                    <i class="far fa-heart fa-2x" id ="like-icon" style="color:red;"></i>
                </span>
                {% endif %}
                <span id="count-likes-{{ post.id }}" class="alt-services-title font-alt">
                    좋아요
                {% if post.like_count == 0 %}
                    0개
                {% else %}
                    {{ post.like_count }}개
                {% endif %}
                </span>
            </span>
            <span href="#" class="dislike" name ="{{post.id}}" value="Dislike">
                {% if user in post.dislike_user_set.all %}
                <span class="alt-service-icon">
                    <i class="fas fa-thumbs-down fa-2x" id ="dislike-icon" style="color:blue;"></i>
                </span>
                {% else %}
                <span class="alt-service-icon">
                    <i class="far fa-thumbs-down fa-2x" id ="dislike-icon" style="color:blue;"></i>
                </span>
                {% endif %}
                <span id="count-dislikes-{{ post.id }}" class="alt-services-title font-alt">
                    싫어요 
                {% if post.dislike_count == 0 %}
                    0개
                {% else %}
                    {{ post.dislike_count }}개
                {% endif %}
                </span>
            </span>
            <br>
            {% if post.writer == user %}
            <a href="{% url 'main:edit' post.id %}"><strong>수정하기 &nbsp</strong></a>
            <a href="{% url 'main:delete' post.id %}"><strong>삭제하기</strong></a>
            {% endif %}
            <hr>
            <div>
                {% if user.is_authenticated %}
                <form action="{%url 'main:create_comment' post.id%}" method="POST">
                    {%csrf_token%}
                    <textarea name="content" placeholder="댓글내용입력" cols="60" rows="3"></textarea>
                    <input type="submit" value="확인">
                </form>
                {% else %}
                <h5>댓글 작성은 로그인 후 이용해주세요.</h5>
                {% endif %}
            </div>
            <hr>
            <div>
                {% for comment in comments %}
                <div>
                    <h5>{{comment.content}}</h5>
                    <p><a href="{% url 'users:mypage' comment.writer.id %}">작성자 : {{comment.writer}}</a></p>
                    {% if comment.writer == user %}
                    <a href="{% url 'main:edit_comment' post.id comment.id %}"><strong>수정하기 &nbsp</strong></a>
                    <a href="{% url 'main:delete_comment' post.id comment.id %}"><strong>삭제하기</strong></a>
                    {% endif %}
                    <hr>
                </div>
                {% endfor %}
            </div>  
    </div>    
</section>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
             type:'POST',
            url:"{% url 'like_toggle' post.id %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.like_count==null){
                    alert('로그인이 필요합니다.');
                     window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='like'){
                       $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart fa-2x');
                    }
                    else{
                         $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart fa-2x');
                     }
                    $('#count-likes-{{post.id}}').html('좋아요 '+response.like_count+"개");
                 }
            },
            error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
         })
    })

    $(".dislike").click(function(){
        var pk=$(this).attr('name')
        $.ajax({
             type:'POST',
            url:"{% url 'dislike_toggle' post.id %}",
            data:{'pk':pk,'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:'json',
            success:function(response){
                if(response.dislike_count==null){
                    alert('로그인이 필요합니다.');
                     window.location.replace('/accounts/login/');
                }
                else{
                    if(response.result=='dislike'){
                       $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down fa-2x');
                    }
                    else{
                         $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-thumbs-down fa-2x');
                     }
                    $('#count-dislikes-{{post.id}}').html('싫어요 '+response.dislike_count+"개");
                 }
            },
            error:function(request, status, error){
                alert("로그인이 필요합니다.")
                alert('code:'+request.status+'\n'+'message:'+request.responseText+"\n"+"error:"+error);
            },
         })
    })
</script>
{% endblock %}

project/main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}
<section>
    <h2>글 수정하기</h1>
    <form action="{% url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목: <input type="text" name="title" value="{{ post.title }}"></p>
        <p>사진: <input type="file" name="image" value=""></p>
        <p>내용: <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
        <button type = "submit">제출</button>
    </form>
</section>
{% endblock %}

project/main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}
<section>
    <h2>댓글 수정하기</h1>
    <form action="{% url 'main:update_comment' post.id comment.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>내용: <textarea type="text" name="content" id="" cols="30" rows="10">{{comment.content}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</section>
{% endblock %}

project/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}
<section>
     {% if user.username == 'yusung' %}
    <div class="new">
        <h2><a href="{%url 'main:new'%}">글 쓰기</a></h2>
    </div>
    {% else %}
    <h3>관리자만 글을 작성할 수 있습니다.</h3>
    {% endif %}
    <h2>Album Review</h2>
    <div class="posts">
        {% for post in posts %}
        <div class="card" style="width: 18rem;">
            <a href="{% url 'main:detail' post.id %}">
                {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">{{post.summary}}...</p>
                </div>
            </a>
          </div>
        {% endfor %}
    </div>    
</section>
{% endblock %}

project/main/templates/main/introduction.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_introduction.css' %}">
{% endblock %}
{% block content %}

<div id="profile" class="box">
    <div class="title">
        <h3>Profile</h3>
    </div>
    <hr>
    <div class="description">
        <div class="picbox padding56">
            <div class="pic">
                <img src="{% static 'images/me_with_alpaca.jpg' %}">
            </div>
        </div>
        <div class="text">
            <h4>안유성</h4>
            <br>
            <p>1999.12.10</p>
            <p>동국대학교 전자전기공학부</p>
            <p>ECR 31기</p>
            <p>멋쟁이사자처럼 10기</p>
        </div>
    </div>
</div>
<div id="education" class="box">
    <div class="title">
        <h3>Education</h3>
    </div>
    <hr>
    <div class="description">
        <ul>
            <li>금곡초등학교 졸업</li>
            <li>솔빛중학교 졸업</li>
            <li>예당고등학교 졸업</li>
            <li>동국대학교 재학 중</li> 
        </ul>    
    </div>
</div>
<div id="taste" class="box">
    <div class="title">
        <h3>Taste</h3>
    </div>
    <hr>
    <div class="description">
        <div id="snack" class="food">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/pringles.jpg' %}">
                </div>
            </div>
            <div class="kind">Snack</div>
            <div class="item">Pringles</div>
        </div> 
        <div id="beer" class="food">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/budweiser.jpg' %}">
                </div>
            </div>
            <div class="kind">Beer</div>
            <div class="item">Budweiser</div>
        </div>
        <div id="bread" class="food">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/papajohns.png' %}">
                </div>
            </div>
            <div class="kind">Pizza</div>
            <div class="item">Papajohn's</div>
        </div>  
    </div>
</div>
<div id="music" class="box">
    <div class="title">
        <h3>Music</h3>
    </div>
    <hr>
    <div class="description">
        <div id="pop" class="album">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/Peach-Pit-from-2-to-3-artwork.jpg' %}">
                </div>
            </div>
            <div class="kind">Pop</div>
            <div class="item">From 2 to 3</div>
        </div> 
        <div id="rock" class="album"> 
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/blueweekend.jpg' %}">
                </div>
            </div>
            <div class="kind">Rock</div>
            <div class="item">Blue Weekend</div>
        </div>
        <div id="hiphop" class="album">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/blonde.jpg' %}">
                </div>
            </div>
            <div class="kind">Hiphop</div>
            <div class="item">Blonde</div>
        </div>
        <div id="folk" class="album">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/the_party.jpg' %}">
                </div>
            </div>
            <div class="kind">Folk</div>
            <div class="item">The Party</div>
        </div>
        <div id="instrumental" class="album">
            <div class="picbox padding100">
                <div class="pic">
                    <img src="{% static 'images/fkj.jpg' %}">
                </div>
            </div>
            <div class="kind">Instrumental</div>
            <div class="item">French Kiwi Juice</div>
        </div>  
    </div>
</div>
{% endblock %}

project/main/templates/main/login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% providers_media_js %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

project/main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">
{% endblock %}

{% block content %}
<section>
    <form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목: <text type="text" name="title" cols="50" rows="10"></p>
        <p>사진: <input type="file" name="image"></p>
        <p>내용: <textarea type="text" name="body" id="" cols="50" rows="10"></textarea></p>
        <button type = "submit">제출</button>
    </form>
</section>
{% endblock %}